package setup

import (
	"net/http"
	"strconv"
	"strings"

	"app/src/api/kitsu"
	"app/src/model"
	"gorm.io/gorm"
)

func renderCurrentIARoutingEditorSetupStyleWithData(db *gorm.DB, r *http.Request, p model.Project, lang, readTable string, view productionNotificationReviewerView) string {
	html := renderCurrentIARoutingEditorMarkupWithData(db, r, p, lang, readTable, view)
	if scriptStart := strings.Index(html, `<script>`); scriptStart >= 0 {
		html = html[:scriptStart]
	}
	panelStart := strings.Index(html, `<section class="production-wfa-edit-panel" data-wfa-detail-panel`)
	if panelStart >= 0 {
		panelEnd := strings.Index(html[panelStart:], `</section>`)
		if panelEnd >= 0 {
			panelEnd += panelStart + len(`</section>`)
			panel := `<section class="production-wfa-edit-panel" data-wfa-detail-panel aria-live="polite" hidden><div class="production-wfa-edit-heading"><h4 data-wfa-title></h4><span>` + esc(t(lang, "WFA通知先", "WFA recipients")) + `</span></div><div class="production-wfa-recipient-row" data-wfa-automatic><span class="production-wfa-recipient-kind">` + esc(t(lang, "Supervisor", "Supervisor")) + `</span><span data-wfa-automatic-value>` + esc(t(lang, "確認中", "Checking")) + `</span></div><div class="production-wfa-recipient-row" data-wfa-additional><span class="production-wfa-recipient-kind">` + esc(t(lang, "追加通知先", "Additional recipients")) + `</span><ul data-wfa-target-list></ul><button type="button" class="btn-ghost production-wfa-add-target" data-wfa-add-target>+ ` + esc(t(lang, "追加", "Add")) + `</button></div></section>`
			html = html[:panelStart] + panel + html[panelEnd:]
		}
	}
	html = strings.Replace(html, `<div hidden data-editor-parking>`, `<div data-editor-parking>`, 1)
	html = strings.Replace(html, `<div class="table-wrap wizard-plan-table">`, `<div class="routing-list-scroll" data-routing-list-scroll><div class="table-wrap wizard-plan-table">`, 1)
	html = strings.Replace(html, `</tbody></table></div><div class="button-row production-routing-editor-actions">`, `</tbody></table></div></div><div class="button-row production-routing-editor-actions">`, 1)
	html = strings.Replace(html, `<div data-editor-parking>`, renderCurrentRoutingRowTemplate(lang, view.TaskTypes, model.ListProjectWebhooks(db, p.KitsuProjectID))+`<div data-editor-parking>`, 1)
	if noteStart := strings.Index(html, `<p class="field-help routing-destructive-note">`); noteStart >= 0 {
		if noteEnd := strings.Index(html[noteStart:], `</p>`); noteEnd >= 0 {
			noteEnd += noteStart + len(`</p>`)
			html = html[:noteStart] + html[noteEnd:]
		}
	}
	html = strings.Replace(html, `data-current-routing-form data-async-notification-apply`, `data-current-routing-form lang="`+esc(lang)+`" data-async-notification-apply`, 1)
	return html + currentRoutingEditorScript() + currentRoutingDeleteScript() + currentRecipientComboboxScript()
}

func renderCurrentRoutingRowTemplate(lang string, taskTypes []kitsu.TaskType, webhooks []model.ProjectWebhook) string {
	var types, destinations strings.Builder
	types.WriteString(`<option value="">` + esc(t(lang, "Task Typeを選択", "Select Task Type")) + `</option>`)
	for _, taskType := range taskTypes {
		types.WriteString(`<option value="` + esc(taskType.ID) + `" data-default-channel-name="` + esc(NormalizeTaskTypeChannelName(taskType.Name)) + `">` + esc(taskType.Name) + `</option>`)
	}
	destinations.WriteString(`<option value="">` + esc(t(lang, "Discordチャンネルを選択", "Select Discord Channel")) + `</option>`)
	for _, webhook := range webhooks {
		name := strings.TrimPrefix(strings.TrimSpace(webhook.ChannelName), "#")
		destinations.WriteString(`<option value="` + strconv.FormatUint(uint64(webhook.ID), 10) + `">#` + esc(name) + `</option>`)
	}
	destinations.WriteString(`<option value="__auto__">` + esc(t(lang, "自動作成", "Automatic")) + `</option><option value="__custom__">` + esc(t(lang, "カスタム...", "Custom...")) + `</option>`)
	return `<template data-routing-row-template><tr draggable="true" data-routing-row data-draft="true" data-task-type="" data-task-type-name="" data-default-channel-name="" data-existing-targets="W10="><td><label class="routing-new-task-type" data-task-selector-wrap><span class="sr-only">Task Type</span><select name="task_type_id" data-task-type-select>` + types.String() + `</select></label><button type="button" class="routing-select-task" data-select-task aria-pressed="false" aria-expanded="false" disabled><span class="routing-task-type-name">` + esc(t(lang, "Task Typeを選択", "Select Task Type")) + `</span><span class="routing-expand-indicator" aria-hidden="true"></span></button></td><td><div class="routing-destination-control"><select class="routing-destination-select" name="destination_mode" data-destination-control aria-label="` + esc(t(lang, "Discordチャンネル", "Discord Channel")) + `" disabled>` + destinations.String() + `</select><label class="routing-custom-channel" data-custom-channel-field hidden><span class="sr-only">` + esc(t(lang, "チャンネル名", "Channel name")) + `</span><input data-new-channel-name maxlength="100" autocomplete="off" disabled></label></div></td><td><details class="routing-row-menu"><summary aria-label="` + esc(t(lang, "行の操作", "Route actions")) + `">&#8942;</summary><div class="routing-row-menu-panel" role="menu"><button type="button" class="routing-remove" data-routing-remove role="menuitem">` + esc(t(lang, "通知対象から外す", "Remove from notifications")) + `</button></div></details></td></tr></template>`
}

func currentRoutingEditorScript() string {
	return `<script>
(function(){
  var form=document.querySelector('[data-current-routing-form]');if(!form)return;
  var body=form.querySelector('[data-current-routing-sort]'),add=form.querySelector('[data-routing-add]'),template=form.querySelector('[data-routing-row-template]');
  var panel=form.querySelector('[data-wfa-detail-panel]'),source=form.parentElement.querySelector('[data-wfa-source] [data-wfa-pending-source]'),message=form.querySelector('[data-apply-message]'),pending=form.querySelector('[data-pending-status]'),apply=form.querySelector('[data-apply-submit]');
  var modal=form.parentElement.querySelector('[data-wfa-add-modal]'),reviewerChanges={},activeRow=null,openMenu=null;
  var initialRoutes=Array.prototype.map.call(body.querySelectorAll('[data-routing-row]'),function(row){return {task_type_id:row.dataset.taskType||'',destination_mode:row.dataset.originalDestination||'',new_channel_name:''}});
  function rows(){return Array.prototype.slice.call(body.querySelectorAll('[data-routing-row]'))}
  function visibleRows(){return rows().filter(function(row){return row.dataset.pendingRemoval!=='true'&&!row.hidden})}
  function typeID(row){var select=row&&row.querySelector('[data-task-type-select]');return select?select.value:(row?row.dataset.taskType:'')}
  function destination(row){return row&&row.querySelector('[data-destination-control]')}
  function targets(row){try{var raw=atob(row.dataset.existingTargets||'W10='),bytes=Uint8Array.from(raw,function(ch){return ch.charCodeAt(0)});return JSON.parse(new TextDecoder().decode(bytes))}catch(_){return []}}
  function delta(id){return reviewerChanges[id]||(reviewerChanges[id]={add_user_ids:[],remove_user_ids:[],add_role_ids:[],remove_role_ids:[]})}
  function selectedOption(select,value){return Array.prototype.find.call(select.options,function(option){return option.value===value})}
  function updateDestination(row){var control=destination(row),field=row.querySelector('[data-custom-channel-field]'),input=row.querySelector('[data-new-channel-name]'),auto=control&&control.querySelector('option[value="__auto__"]');if(auto)auto.textContent=(form.lang==='ja'?'自動作成: #':'Auto create: #')+(row.dataset.defaultChannelName||'');var custom=!!control&&control.value==='__custom__';if(field)field.hidden=!custom;if(input){input.disabled=!custom;if(custom&&!input.value)input.value=row.dataset.newChannelName||row.dataset.defaultChannelName||'';row.dataset.newChannelName=input.value}if(control)row.dataset.destinationMode=control.value}
  function renderTargets(row){var list=panel.querySelector('[data-wfa-target-list]');if(!list)return;list.textContent='';var id=typeID(row),changes=delta(id),items=targets(row).filter(function(item){return changes[item.kind==='role'?'remove_role_ids':'remove_user_ids'].indexOf(item.id)<0});['user','role'].forEach(function(kind){changes[kind==='role'?'add_role_ids':'add_user_ids'].forEach(function(targetID){var select=modal&&modal.querySelector(kind==='role'?'[data-wfa-role-id]':'[data-wfa-user-id]'),option=select&&selectedOption(select,targetID);items.push({kind:kind,id:targetID,label:option?option.textContent:(kind==='role'?'@'+targetID:targetID)})})});items.forEach(function(item){var li=document.createElement('li'),name=document.createElement('span'),button=document.createElement('button');li.dataset.kind=item.kind;li.dataset.id=item.id;name.textContent=item.label;button.type='button';button.className='btn-ghost';button.dataset.wfaRemoveTarget='';button.textContent=form.dataset.removeLabel;li.appendChild(name);li.appendChild(button);list.appendChild(li)})}
  function selectRow(row){if(!row||row.dataset.pendingRemoval==='true'||!typeID(row))return;activeRow=row;rows().forEach(function(item){var selected=item===row;item.classList.toggle('selected',selected);var button=item.querySelector('[data-select-task]');if(button){button.setAttribute('aria-pressed',String(selected));button.setAttribute('aria-expanded',String(selected))}});panel.hidden=false;panel.querySelector('[data-wfa-title]').textContent=row.dataset.taskTypeName||'';var match=source&&source.querySelector('[data-task-type-id="'+CSS.escape(typeID(row))+'"]'),sourceAuto=match&&match.querySelector('[data-wfa-automatic-value]'),auto=panel.querySelector('[data-wfa-automatic-value]');if(auto)auto.textContent=sourceAuto?(sourceAuto.dataset.wfaSummary||sourceAuto.textContent):form.dataset.emptyWfa;renderTargets(row);sync()}
  function routeSnapshot(){return visibleRows().map(function(row){var control=destination(row),input=row.querySelector('[data-new-channel-name]');return {task_type_id:typeID(row),destination_mode:control?control.value:'',new_channel_name:control&&control.value==='__custom__'&&input?input.value.trim():''}})}
  function targetChangeCount(){var live=new Set(visibleRows().map(typeID));return Object.keys(reviewerChanges).reduce(function(total,id){if(!live.has(id))return total;var c=reviewerChanges[id];return total+c.add_user_ids.length+c.remove_user_ids.length+c.add_role_ids.length+c.remove_role_ids.length},0)}
  function sync(){var chosen={};visibleRows().forEach(function(row){var id=typeID(row);if(id)chosen[id]=(chosen[id]||0)+1});body.querySelectorAll('[data-task-type-select] option').forEach(function(option){if(!option.value)return;var owner=option.closest('[data-routing-row]');option.disabled=!!chosen[option.value]&&typeID(owner)!==option.value});var live=visibleRows(),persisted=live.some(function(row){return row.dataset.draft!=='true'}),valid=live.length>0&&live.every(function(row){var id=typeID(row),control=destination(row),mode=control&&control.value,input=row.querySelector('[data-new-channel-name]');return !!id&&!!mode&&(mode!=='__auto__'||!!row.dataset.defaultChannelName)&&(mode!=='__custom__'||!!(input&&input.value.trim()))});body.querySelectorAll('[data-routing-remove]').forEach(function(button){button.disabled=live.length<=1&&persisted});var routeChanged=JSON.stringify(routeSnapshot())!==JSON.stringify(initialRoutes),count=(routeChanged?1:0)+targetChangeCount();if(pending)pending.textContent=count===0?form.dataset.noPending:(count+' '+(count===1?form.dataset.pendingOne:form.dataset.pendingMany));if(apply)apply.disabled=count===0||!valid}
  function bindRow(row){if(row.dataset.eventsBound==='true')return;row.dataset.eventsBound='true';var taskSelect=row.querySelector('[data-task-type-select]'),select=row.querySelector('[data-select-task]'),control=destination(row),typeWrap=row.querySelector('[data-task-selector-wrap]');if(taskSelect)taskSelect.addEventListener('change',function(){var option=taskSelect.selectedOptions[0];row.dataset.taskType=taskSelect.value;row.dataset.taskTypeName=option?option.textContent:'';row.dataset.defaultChannelName=option?option.dataset.defaultChannelName||'':'';row.dataset.existingTargets='W10=';if(select){select.disabled=!taskSelect.value;select.querySelector('.routing-task-type-name').textContent=row.dataset.taskTypeName||form.dataset.draftLabel}if(typeWrap)typeWrap.hidden=!!taskSelect.value;if(control){control.disabled=!taskSelect.value;control.value=taskSelect.value?'__auto__':''}updateDestination(row);sync()});if(select)select.addEventListener('click',function(){selectRow(row)});if(control){control.addEventListener('change',function(){updateDestination(row);sync()});row.querySelector('[data-new-channel-name]')?.addEventListener('input',function(){row.dataset.newChannelName=this.value;sync()})}row.querySelector('[data-routing-remove]')?.addEventListener('click',function(){var menu=row.querySelector('.routing-row-menu');if(menu)menu.open=false;if(row.dataset.draft==='true'){row.remove();if(activeRow===row){activeRow=null;panel.hidden=true;rows().forEach(function(item){item.classList.remove('selected');item.querySelector('[data-select-task]')?.setAttribute('aria-expanded','false')})}}else{if(visibleRows().length<=1||!window.confirm(form.dataset.removeConfirm||''))return;row.dataset.pendingRemoval='true';row.hidden=true;if(activeRow===row){activeRow=null;panel.hidden=true;rows().forEach(function(item){item.classList.remove('selected');item.querySelector('[data-select-task]')?.setAttribute('aria-expanded','false')})}}sync()});row.querySelector('.routing-row-menu')?.addEventListener('toggle',function(event){var details=event.currentTarget;if(!details.open){if(openMenu===details)openMenu=null;return}if(openMenu&&openMenu!==details)openMenu.open=false;openMenu=details;requestAnimationFrame(function(){var summary=details.querySelector('summary'),menu=details.querySelector('.routing-row-menu-panel');if(!summary||!menu)return;var rect=summary.getBoundingClientRect(),width=menu.getBoundingClientRect().width||190,height=menu.getBoundingClientRect().height||100,left=Math.max(8,Math.min(innerWidth-width-8,rect.right-width)),top=rect.bottom+6;if(top+height>innerHeight-8)top=Math.max(8,rect.top-height-6);menu.style.position='fixed';menu.style.left=left+'px';menu.style.top=top+'px';menu.style.right='auto'})});updateDestination(row)}
  rows().forEach(bindRow);document.addEventListener('pointerdown',function(event){if(openMenu&&!openMenu.contains(event.target))openMenu.open=false});document.addEventListener('keydown',function(event){if(event.key==='Escape'&&openMenu){openMenu.open=false;openMenu.querySelector('summary')?.focus()}});window.addEventListener('resize',function(){if(openMenu)openMenu.open=false});
  if(add)add.addEventListener('click',function(){if(!template||!template.content.firstElementChild)return;var row=template.content.firstElementChild.cloneNode(true);row.dataset.draft='true';var control=destination(row);if(control){control.value='__auto__';control.disabled=true}body.appendChild(row);bindRow(row);row.querySelector('[data-task-type-select]')?.focus();sync()});
  panel.addEventListener('click',function(event){var button=event.target.closest('[data-wfa-remove-target]');if(!button||!activeRow)return;var li=button.closest('li'),id=typeID(activeRow),kind=li.dataset.kind,targetID=li.dataset.id,c=delta(id),base=targets(activeRow).some(function(item){return item.kind===kind&&item.id===targetID}),key=kind==='role'?'remove_role_ids':'remove_user_ids',addKey=kind==='role'?'add_role_ids':'add_user_ids';if(base){if(c[key].indexOf(targetID)<0)c[key].push(targetID)}else c[addKey]=c[addKey].filter(function(value){return value!==targetID});renderTargets(activeRow);sync()});panel.querySelector('[data-wfa-add-target]')?.addEventListener('click',function(){if(activeRow&&modal&&modal.showModal){modal.dataset.recipientMode='user';modal.querySelector('#wfa-user-tab')?.click();modal.showModal()}});
  modal?.querySelectorAll('[role="tab"]').forEach(function(tab,index,tabs){tab.addEventListener('click',function(){var mode=tab.dataset.recipientMode;modal.dataset.recipientMode=mode;modal.querySelectorAll('[role="tab"]').forEach(function(item){var selected=item===tab;item.setAttribute('aria-selected',String(selected));item.tabIndex=selected?0:-1});modal.querySelectorAll('[data-recipient-panel]').forEach(function(item){item.hidden=item.dataset.recipientPanel!==mode})});tab.addEventListener('keydown',function(event){if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();var next=event.key==='Home'?0:event.key==='End'?tabs.length-1:event.key==='ArrowRight'?(index+1)%tabs.length:(index+tabs.length-1)%tabs.length;tabs[next].click();tabs[next].focus()})});modal?.querySelector('[data-wfa-add-cancel]')?.addEventListener('click',function(){modal.close()});modal?.querySelector('[data-wfa-add-confirm]')?.addEventListener('click',function(){if(!activeRow)return;var kind=modal.dataset.recipientMode,select=modal.querySelector(kind==='role'?'[data-wfa-role-id]':'[data-wfa-user-id]'),id=select&&select.value;if(!id)return;var c=delta(typeID(activeRow)),base=targets(activeRow).some(function(item){return item.kind===kind&&item.id===id}),key=kind==='role'?'add_role_ids':'add_user_ids',removeKey=kind==='role'?'remove_role_ids':'remove_user_ids';if(base)c[removeKey]=c[removeKey].filter(function(value){return value!==id});else if(c[key].indexOf(id)<0)c[key].push(id);select.value='';modal.close();renderTargets(activeRow);sync()});
  form.addEventListener('submit',async function(event){event.preventDefault();message.textContent='';var routes=visibleRows().map(function(row){var control=destination(row),id=typeID(row),mode=control.value,route={task_type_id:id};if(mode==='__auto__')route.create_channel_name=row.dataset.defaultChannelName||'';else if(mode==='__custom__')route.create_channel_name=(row.querySelector('[data-new-channel-name]')?.value||'').trim();else route.destination_webhook_id=Number(mode);return route});var live=new Set(routes.map(function(route){return route.task_type_id})),changes=Object.keys(reviewerChanges).filter(function(id){var c=reviewerChanges[id];return live.has(id)&&(c.add_user_ids.length||c.remove_user_ids.length||c.add_role_ids.length||c.remove_role_ids.length)}).map(function(id){var c=reviewerChanges[id];return {task_type_id:id,add_user_ids:c.add_user_ids,remove_user_ids:c.remove_user_ids,add_role_ids:c.add_role_ids,remove_role_ids:c.remove_role_ids}}),payload={project_id:form.dataset.projectId,expected_revision:form.querySelector('[name="expected_revision"]').value,routes:routes,reviewer_changes:changes};apply.disabled=true;try{var response=await fetch(form.dataset.applyEndpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload),credentials:'same-origin'});if(response.status===409){message.textContent=form.dataset.staleMessage;return}if(!response.ok){message.textContent=form.dataset.errorMessage;return}window.location.assign(form.dataset.successUrl)}catch(_){message.textContent=form.dataset.errorMessage}finally{sync()}});
  rows().forEach(function(row){row.addEventListener('dragstart',function(event){event.dataTransfer.setData('text/plain',row.dataset.taskType||'');row.classList.add('is-dragging')});row.addEventListener('dragend',function(){row.classList.remove('is-dragging')});row.addEventListener('dragover',function(event){event.preventDefault()});row.addEventListener('drop',function(event){event.preventDefault();var id=event.dataTransfer.getData('text/plain'),dragged=rows().find(function(item){return item.dataset.taskType===id});if(!dragged||dragged===row||dragged.dataset.draft==='true')return;body.insertBefore(dragged,row);sync()})});sync();
})();
</script>`
}
