#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
helper="${root}/deploy/kitsusync-staging-deploy"
bootstrap="${root}/deploy/kitsusync-staging-bootstrap"
compose="${root}/deploy/kitsusync-staging-compose.yml"
candidate_deploy="${root}/scripts/deploy-kitsusync-staging-candidate.ps1"
staging_workflow="${root}/.github/workflows/staging-deploy.yml"

bash "${root}/scripts/test-staging-candidate-download-contract.sh"
bash "${root}/scripts/test-staging-network-membership.sh"
bash -n "${helper}"
bash -n "${bootstrap}"
grep -Fq 'set -Eeuo pipefail' "${helper}"
grep -Fq 'set -Eeuo pipefail' "${bootstrap}"
grep -Fq 'KITSUSYNC_DISABLE_POLL: "1"' "${compose}"
grep -Fq '127.0.0.1:8091:8090' "${compose}"
grep -Fq './conf.toml:/app/conf.toml:ro' "${compose}"
grep -Fq 'name: kitsusync-staging-data' "${compose}"
grep -Fq 'internal: false' "${compose}"
! grep -Eq 'KITSU_HOSTNAME|DISCORD_(BOT_TOKEN|GUILD_ID|WEBHOOK_URL)' "${compose}"
! grep -Eq 'tpl|127\.0\.0\.1:8090:|/var/lib/kitsusync-deploy|kitsusync-deploy-transaction' "${compose}"
grep -Fq 'cat > /etc/kitsusync-staging/conf.toml' "${bootstrap}"
grep -Fq 'chmod 0400 /etc/kitsusync-staging/conf.toml' "${bootstrap}"
grep -Fq 'kitsusync:ci-${SOURCE_SHA}' "${helper}"
grep -Fq 'image_config_digest' "${helper}"
grep -Fq 'image_content_digest' "${helper}"
grep -Fq 'O_NOFOLLOW' "${helper}"
grep -Fq 'STAGING_VOLUME_PREEXISTS' "${helper}"
grep -Fq 'STAGING_NETWORK_PREEXISTS' "${helper}"
grep -Fq 'STAGING_NETWORK_EGRESS_UNAVAILABLE' "${helper}"
grep -Fq 'STAGING_DISCORD_ENV_ISOLATION_INVALID' "${helper}"
grep -Fq 'STAGING_KITSU_NETWORK=DEFAULT_EGRESS_AVAILABLE' "${helper}"
grep -Fq "docker network inspect --format '{{json .Containers}}' kitsusync-staging-network" "${helper}"
grep -Fq 'prod_before=' "${helper}"
grep -Fq 'verify_production_unchanged || die PRODUCTION_RUNTIME_CHANGED' "${helper}"
grep -Fq 'verify_production_unchanged || rollback_status=1' "${helper}"
grep -Fq -- "--max-time 1" "${helper}"
! grep -Fq 'STAGING_EGRESS_NETWORK_INVALID' "${helper}"
! grep -Fq 'internal: true' "${compose}"
grep -Fq 'CURRENT_STAGING_SOURCE_INVALID' "${helper}"
grep -Fq 'docker ps -a --filter' "${helper}"
grep -Fq 'STAGING_CONFIG_FILE_UNSAFE' "${helper}"
grep -Fq 'STAGING_MOUNT_ISOLATION_INVALID' "${helper}"
grep -Fq 'kitsusync-staging-network' "${helper}"
grep -Fq 'STAGING_NETWORK_ATTACHMENT_COUNT_INVALID' "${helper}"
grep -Fq 'STAGING_NETWORK_NAME_INVALID' "${helper}"
grep -Fq 'STAGING_NETWORK_MEMBERSHIP_INVALID' "${helper}"
grep -Fq 'max_attempts=15' "${helper}"
grep -Fq 'STAGING_NETWORK_MEMBERSHIP_DIAGNOSTIC' "${helper}"
grep -Fq 'STAGING_HELPER_CONTRACT=staging-v5' "${helper}"
grep -Fq 'wait_staging_http health "$SOURCE_SHA"' "${helper}"
grep -Fq 'wait_staging_http ready "$SOURCE_SHA"' "${helper}"
grep -Fq 'wait_staging_http admin-users "$SOURCE_SHA"' "${helper}"
grep -Fq 'wait_staging_http admin-health "$SOURCE_SHA"' "${helper}"
grep -Fq 'wait_staging_http admin-users "$previous_sha"' "${helper}"
grep -Fq 'wait_staging_http admin-health "$previous_sha"' "${helper}"
! grep -Eq 'curl .*127\.0\.0\.1:8091/(health|ready|bot/admin)' "${helper}"
grep -Fq 'STAGING_HTTP_WAIT_FAILED endpoint=%s attempts=%s' "${helper}"
grep -Fq 'STAGING_HELPER_CONTRACT=staging-v5' "${helper}"
grep -Fq 'STAGING_REQUIRE_DOCKER_FIXTURE: "1"' "${root}/.github/workflows/build.yml"
grep -Fq 'b43df984dd87321c4f9eb76478557b23db35cac8986b01ddd4b3af5a2353e5ae' "${root}/deploy/kitsusync-staging-helper-upgrade-root.sh"
grep -Fq 'scripts/test-staging-http-readiness.sh' "${root}/scripts/test-staging-candidate-download-contract.sh"
grep -Fq 'STAGING_REQUIRE_DOCKER_FIXTURE: "1"' "${root}/.github/workflows/build.yml"
! grep -Fq 'die STAGING_NETWORK_COUNT_INVALID' "${helper}"
! grep -Eq 'kitsusync-preview-deploy|kitsusync-deploy-transaction' "${helper}"
grep -Fq 'prior-staging.sqlite' "${helper}"
grep -Fq 'STAGING_DATABASE_BACKUP_FAILED' "${helper}"
grep -Fq 'STAGING_DATABASE_INVALID' "${helper}"
grep -Fq 'STAGING_RUNTIME_SECRET_INVALID' "${helper}"
grep -Fq 'prior-runtime-secret-absent' "${helper}"
grep -Fq 'STAGING_ROLLBACK=PREVIOUS_CANDIDATE_AND_DATA' "${helper}"
grep -Fq 'STAGING_RUNTIME_SOURCE_MISMATCH' "${helper}"
grep -Fq 'PRODUCTION_RUNTIME_CHANGED' "${helper}"
! grep -Eq '/etc/kitsusync-deploy|/var/lib/kitsusync-deploy|--project-name kitsusync([[:space:]]|$)' "${helper}"
grep -Fq 'NOPASSWD: /usr/local/sbin/kitsusync-staging-deploy *' "${bootstrap}"
! grep -Fq 'vfxstudio-breakglass' "${candidate_deploy}"
! grep -Fq 'upgrade-root.sh' "${candidate_deploy}"
grep -Fq 'scripts/upgrade-kitsusync-staging-helper.ps1' "${root}/docs/deployment/KITSUSYNC-STAGING.md"
grep -Fq 'workflow_run:' "${staging_workflow}"
grep -Fq 'workflows: [Security Audit]' "${staging_workflow}"
grep -Fq 'cancel-in-progress: true' "${staging_workflow}"
grep -Fq 'id-token: write' "${staging_workflow}"
grep -Fq 'tailscale/github-action@780049a30b6ff5c378a9e7b389d15ece7a204888' "${staging_workflow}"
grep -Fq 'scripts/deploy-kitsusync-staging-candidate.ps1' "${staging_workflow}"
! grep -Fq 'runs-on: self-hosted' "${staging_workflow}"
! grep -Eq 'docker group|NOPASSWD: ALL|/usr/local/sbin/kitsusync-deploy([[:space:]]|$)' "${bootstrap}"
KITSUSYNC_IMAGE_TAG=ci-staging-contract docker compose --project-name kitsusync-staging-contract --file "${compose}" config -q
printf 'staging-deployment-contract=PASS\n'
